Repository luxoncorp/luxon, pull requests merged in 2021-03, with the labels that each got.

#9 Feature/Add navbar responsive support
  app/components/navbar/index.tsx
  app/components/search_bar/index.tsx
  app/components/search_bar/search_bar.module.css
  app/hooks/useDimensions.tsx
  app/styles/globlal.css
Labels: enhancement

#29 add/favoritesMathstoDB
  app/components/match_card/index.tsx
  firebase/client.ts
  utils/database/index.ts
Labels: enhancement

#28 Feature/footer
  .gitignore
  app/components/footer/footer.module.css
  app/components/footer/index.tsx
  pages/favorites/index.tsx
  pages/index.tsx
  pages/profile/index.tsx
Labels: enhancement

#35 Add video-chat room layout
  app/components/footer/footer.module.css
  package-lock.json
  package.json
  pages/live/[id].tsx
  pages/live/live.module.css
Labels: enhancement

#34 Feature/match details layout
  .gitignore
  app/components/footer/footer.module.css
  app/components/login_layout/login_layout.module.css
  app/components/match_details_layout/index.tsx
  app/components/match_details_layout/match_details_layout.module.css
  app/styles/404.module.css
  pages/404.tsx
  pages/details/details.module.css
  pages/details/index.tsx
  public/images/icons/videoConference.png
  public/images/img404.jpg
Labels: enhancement

#39 Add live chat
  firebase/client.ts
  pages/live/[id].tsx
  pages/live/live.module.css
Labels: enhancement

#45 Add meta info for each page
  pages/details/index.tsx
  pages/favorites/index.tsx
  pages/index.tsx
  pages/live/[id].tsx
  pages/login/index.tsx
  pages/profile/index.tsx
  pages/signup/index.tsx
  public/favicon.ico
Labels: enhancement

#42 Fetch favorite user matches from Firebase
  app/components/match_card/index.tsx
  app/context/state.tsx
  pages/favorites/index.tsx
  pages/index.tsx
Labels: enhancement

#38 Feature/data competition
  app/components/championship_card/championship_card.module.css
  app/components/championship_card/index.tsx
  app/components/game_card/game_card.module.css
  app/components/game_card/index.tsx
  app/components/navbar/index.tsx
  app/components/row/index.tsx
  app/components/row/row.module.css
  app/components/scroll_slider/index.tsx
  app/components/scroll_slider/scroll_slider.module.css
  app/components/shields/index.ts
  app/components/table_body/index.tsx
  app/components/table_body/table_body.module.css
  app/context/state.tsx
  app/styles/index.module.css
  pages/api/competitions/[...params].ts
  pages/competition/competition.module.css
  pages/competition/index.tsx
  pages/competition/scorers/index.tsx
  pages/competition/standings/index.tsx
  pages/competition/standings/standings.module.css
  pages/profile/profile.module.css
  public/images/BL1.png
  public/images/CL.png
  public/images/DED.png
  public/images/EL.png
  public/images/FL1.png
  public/images/PD.png
  public/images/PL.png
  public/images/PPL.png
  public/images/SA.png
Labels: enhancement

#47 Feature/standing and scorers
  app/components/navbar/index.tsx
  app/components/table_body/index.tsx
  app/styles/globlal.css
  app/styles/index.module.css
  pages/competition/index.tsx
  pages/competition/standings/standings.module.css
  pages/index.tsx
Labels: enhancement

#49 Move unnecessary redirect to favorites page
  app/components/navbar/index.tsx
  pages/favorites/index.tsx
Labels: bug

#58 Improve styles
  app/components/navbar/index.tsx
  app/components/navbar/navbar.module.css
  pages/live/live.module.css
Labels: enhancement

#55 Delete unnecessary logs
  app/components/match_details_layout/index.tsx
  pages/competition/index.tsx
  pages/live/[id].tsx
  pages/profile/index.tsx
Labels: invalid

#53 Remove unnecessary redirect after signup
  pages/signup/index.tsx
Labels: bug

#54 Fix chatbox overflow in Firefox
  pages/live/[id].tsx
  pages/live/live.module.css
Labels: bug
